version: '3'

services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travelwithus_test
      MYSQL_USER: travelwithus
      MYSQL_PASSWORD: travelwithus
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travelwithus_test
      MYSQL_USER: travelwithus
      MYSQL_PASSWORD: travelwithus
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

  nuxt:
    build: .
    container_name: nuxt-web
    tty: true
    #command: npm run start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
 
volumes:
  mysql: