version: '3'

services:

  mysql:
    container_name: database-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travelwithus_test
      MYSQL_USER: travelwithus
      MYSQL_PASSWORD: travelwithus
      TZ: 'Asia/Tokyo'
    expose:
      - '3306'
    ports:
      - "3316:3306"
    networks:
      - app-net
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travelwithus_test
      MYSQL_USER: travelwithus
      MYSQL_PASSWORD: travelwithus
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app-net

  nuxt:
    build: .
    container_name: nuxt-web
    tty: true
    #command: npm run start
    volumes:
      - .:/app
    ports:
      - "80:3000"
    networks:
      - app-net
 
networks:
  app-net:
    driver: bridge